#ifndef STATIM_TOKEN_H_
#define STATIM_TOKEN_H_

#include "core.h"
#include "metadata.h"

/// Potential kinds of tokens.
typedef enum StmTokenKind {
    STM_TOKEN_KIND_IDENTIFIER,
    STM_TOKEN_KIND_LINE_COMMENT,
    STM_TOKEN_KIND_BLOCK_COMMENT,
    STM_TOKEN_KIND_END_OF_FILE,
    STM_TOKEN_KIND_SET_BRACE,
    STM_TOKEN_KIND_END_BRACE,
    STM_TOKEN_KIND_SET_PAREN,
    STM_TOKEN_KIND_END_PAREN,
    STM_TOKEN_KIND_SET_BRACKET,
    STM_TOKEN_KIND_END_BRACKET,
    STM_TOKEN_KIND_AT,
    STM_TOKEN_KIND_HASH,
    STM_TOKEN_KIND_SIGN,
    STM_TOKEN_KIND_PLUS,
    STM_TOKEN_KIND_PLUS_PLUS,
    STM_TOKEN_KIND_PLUS_EQUALS,
    STM_TOKEN_KIND_MINUS,
    STM_TOKEN_KIND_MINUS_MINUS,
    STM_TOKEN_KIND_MINUS_EQUALS,
    STM_TOKEN_KIND_STAR,
    STM_TOKEN_KIND_STAR_EQUALS,
    STM_TOKEN_KIND_SLASH,
    STM_TOKEN_KIND_SLASH_EQUALS,
    STM_TOKEN_KIND_PERCENT,
    STM_TOKEN_KIND_PERCENT_EQUALS,
    STM_TOKEN_KIND_EQUALS,
    STM_TOKEN_KIND_EQUALS_EQUALS,
    STM_TOKEN_KIND_BANG,
    STM_TOKEN_KIND_BANG_EQUALS,
    STM_TOKEN_KIND_LEFT,
    STM_TOKEN_KIND_LEFT_LEFT,
    STM_TOKEN_KIND_LEFT_EQUALS,
    STM_TOKEN_KIND_RIGHT,
    STM_TOKEN_KIND_RIGHT_RIGHT,
    STM_TOKEN_KIND_RIGHT_EQUALS,
    STM_TOKEN_KIND_AND,
    STM_TOKEN_KIND_AND_AND,
    STM_TOKEN_KIND_AND_EQUALS,
    STM_TOKEN_KIND_OR,
    STM_TOKEN_KIND_OR_OR,
    STM_TOKEN_KIND_OR_EQUALS,
    STM_TOKEN_KIND_XOR,
    STM_TOKEN_KIND_XOR_EQUALS,
    STM_TOKEN_KIND_SKINNY_ARROW,
    STM_TOKEN_KIND_FAT_ARROW,
    STM_TOKEN_KIND_DOT,
    STM_TOKEN_KIND_COMMA,
    STM_TOKEN_KIND_COLON,
    STM_TOKEN_KIND_PATH,
    STM_TOKEN_KIND_SEMICOLON,
    STM_TOKEN_KIND_APOSTROPHE,
    STM_TOKEN_KIND_TILDE,
    STM_TOKEN_KIND_GRAVE,
    STM_TOKEN_KIND_LITERAL_INTEGER,
    STM_TOKEN_KIND_LITERAL_FLOAT,
    STM_TOKEN_KIND_LITERAL_CHARACTER,
    STM_TOKEN_KIND_LITERAL_STRING,
} StmTokenKind;

/// A token lexed from source code.
typedef struct StmToken {
    StmTokenKind     kind;
    StmMetadata      meta;
    char*           pValue;
} StmToken;

STM_API_ATTR const char* STM_API_CALL stmStringifyToken(StmTokenKind kind);

#endif // STATIM_TOKEN_H_
